version: '3.1'
services:
  web:
    image: odoo:14.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - /C/Users/joaqu/Documents/Clase/Git2DAM/SGE/docker/addons
      - /C/Users/joaqu/Documents/Clase/Git2DAM/SGE/docker/config
      - /C/Users/joaqu/Documents/Clase/Git2DAM/SGE/docker/odooodoo-web-data
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo